# Use the jupyter/all-spark-notebook as the base image
FROM jupyter/all-spark-notebook

# Set the working directory
WORKDIR /usr/local/spark/jars

# Download the spark-sql-kafka-0-10_2.12:3.5.0 JAR
USER root
RUN wget https://central.sonatype.com/artifact/org.apache.spark/spark-sql-kafka-0-10_2.12/3.5.0/jar -O spark-sql-kafka-0-10_2.12-3.5.0.jar

# Switch back to the non-root user (default in jupyter images)
USER jovyan

# Set the working directory back to the home directory
WORKDIR /home/jovyan
