# Use Node v21.5.0 as a base image
FROM node:21.5.0

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle your app's source code inside the Docker image
COPY . .

# Define the command to run your app
CMD [ "node", "index.js" ]
