{
 "title": "VIenna public transport Delays",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Limit", "query": "0, 10, 20, 50, 100 " },
   {
    "name": "line",
    "query": "SELECT DISTINCT line FROM shapes ORDER BY line;"
   }
  ]
 },
 "panels": [
  { "title": "General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disruptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n   COUNT(*) as disruption_count\r\n FROM\r\n   delays"
    }
   ]
  },
  {
   "title": "Total Disruptions in selected TImeframe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n   COUNT(*) as disruption_count\r\n FROM\r\n   delays\r\nWHERE\r\n  $__timeFilter(time_start)"
    }
   ]
  },
  {
   "title": "Stations with all time disruption count",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  station_name AS \"Station\",\r\n  COUNT(*) AS \"Disruptions\"\r\nFROM\r\n  (SELECT jsonb_array_elements_text(stations) AS station_name FROM delays) AS subquery\r\nGROUP BY\r\n  station_name\r\nORDER BY\r\n  \"Disruptions\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "All time resons for disruptions",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  title as \"Disruption reason\",\r\n  count(*) as \"Count\"\r\nFROM\r\n  delays \r\nGROUP BY\r\n  title\r\nORDER BY\r\n  count(*) DESC;\r\n"
    }
   ]
  },
  {
   "title": "Stations with disruption count within selected timeframe",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  station_name AS \"Station\",\r\n  COUNT(*) AS \"Disruptions\"\r\nFROM\r\n  (SELECT jsonb_array_elements_text(stations) AS station_name FROM delays WHERE $__timeFilter(time_start)) AS subquery\r\nGROUP BY\r\n  station_name\r\nORDER BY\r\n  \"Disruptions\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Resons for disruptions in selected timeframe",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  title as \"Disruption reason\",\r\n  count(*) as \"Count\"\r\nFROM\r\n  delays\r\nWHERE \r\n  $__timeFilter(delays.time_start) \r\nGROUP BY\r\n  title\r\nORDER BY\r\n  count(*) DESC;\r\n"
    }
   ]
  },
  { "title": "Geo and Historic Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Weather and Disruptions over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT time, relative_humidity_2m, temperature_2m, wind_speed_10m FROM weather_data WHERE $__timeFilter(time);"
    },
    {
     "rawSql": "SELECT\r\n  time_start AS time,\r\n  COUNT(*) AS delays\r\nFROM\r\n  delays\r\nWHERE\r\n  $__timeFilter(time_start)\r\nGROUP BY\r\n  time_start;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  time_start AS time,\r\n  COUNT(*) AS top_10_highest_disruptions_count\r\nFROM\r\n  delays\r\nWHERE\r\n  $__timeFilter(time_start)\r\nGROUP BY\r\n  time_start\r\nORDER BY\r\n  top_10_highest_disruptions_count DESC\r\nLIMIT ('${Limit:raw}');"
    }
   ]
  },
  {
   "title": "Disruptions Heatmap",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT name, latitude, longitude FROM stops"
    },
    {
     "rawSql": "SELECT\r\n  stops.name as \"Station\",\r\n  COUNT(*) as \"Delays\",\r\n  stops.longitude,\r\n  stops.latitude\r\nFROM\r\n  delays\r\nCROSS JOIN\r\n  jsonb_array_elements_text(delays.stations) as station_name\r\nJOIN\r\n  stops ON station_name = stops.name\r\nWHERE \r\n  $__timeFilter(delays.time_start)\r\nGROUP BY\r\n  stops.name, stops.longitude, stops.latitude;\r\n"
    },
    {
     "rawSql": "SELECT * FROM shapes WHERE line = '$line'"
    }
   ]
  },
  {
   "title": "Delays",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT time_start_original as \"Time Start\", title as \"Title\", behoben as \"Behoben\", lines as \"Lines\", stations as \"Stations\" FROM delays WHERE $__timeFilter(time_start) order by time_start_original desc LIMIT 1000;"
    }
   ]
  }
 ]
}