{
 "title": "Vienna Public Transport - Station Overview",
 "time": { "from": "2024-06-16T22:00:00.000Z", "to": "2024-06-30T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Station",
    "label": "Station",
    "query": "select distinct name from stops"
   }
  ]
 },
 "panels": [
  {
   "title": "Disruptions",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_start_original as \"Time Start\",\r\n  id_delays as \"Link\",\r\n  title as \"Title\",\r\n  behoben as \"Behoben\",\r\n  lines as \"Lines\",\r\n  stations as \"Stations\"\r\nFROM\r\n  delays\r\nWHERE\r\n  $__timeFilter(time_start)\r\n  AND ('${Station:raw}') = ANY (SELECT jsonb_array_elements_text(stations));\r\n"
    }
   ]
  },
  {
   "title": "$Station Total Delays",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n   stops.name,\r\n   COUNT(*) as disruption_count\r\n FROM\r\n   delays\r\n CROSS JOIN\r\n   jsonb_array_elements_text(delays.stations) as station_name\r\n JOIN\r\n   stops ON station_name = stops.name\r\nWHERE stops.name = ('${Station:raw}')\r\nGROUP BY\r\n   stops.name"
    }
   ]
  },
  {
   "title": "$Station Delays in selected Timeframe",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n   stops.name,\r\n   COUNT(*) as disruption_count\r\n FROM\r\n   delays\r\n CROSS JOIN\r\n   jsonb_array_elements_text(delays.stations) as station_name\r\n JOIN\r\n   stops ON station_name = stops.name\r\nWHERE stops.name = ('${Station:raw}') AND $__timeFilter(delays.time_start)\r\nGROUP BY\r\n   stops.name"
    }
   ]
  },
  {
   "title": "Weather and Disruptions over time",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time, relative_humidity_2m, temperature_2m, wind_speed_10m FROM weather_data WHERE $__timeFilter(time);"
    },
    {
     "rawSql": "SELECT\r\n  time_start AS time,\r\n  COUNT(*) AS delays\r\nFROM\r\n  delays\r\nWHERE\r\n  ('${Station:raw}') = ANY (SELECT jsonb_array_elements_text(stations)) AND \r\n  $__timeFilter(time_start)\r\nGROUP BY\r\n  time_start;\r\n"
    }
   ]
  }
 ]
}