{
 "title": "VIenna public transport Delays",
 "time": { "from": "2021-10-30T06:53:16.352Z", "to": "2022-01-28T02:31:11.807Z" },
 "panels": [
  {
   "title": "Weather and Delays Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, relative_humidity_2m, temperature_2m, wind_speed_10m FROM weather_data WHERE $__timeFilter(time);"
    },
    {
     "rawSql": "select time_start as time, count(*) as delays from delays WHERE $__timeFilter(time_start) group by time_start "
    }
   ]
  },
  {
   "title": "Stops",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT * FROM stops LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Delays",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT title as \"Title\", behoben as \"Behoben\", lines as \"Lines\", stations as \"Stations\", time_start_original as \"Time Start\" FROM delays LIMIT 50 "
    }
   ]
  }
 ]
}