# Start with a Miniconda base image
FROM conda/miniconda3

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN conda config --set always_yes yes \
    && conda env create -f conda_env.yml \
    && conda activate vptwc \
    && conda clean -afy

# Activate the environment and ensure it is used in the container
ENV PATH="/opt/conda/envs/vptwc/bin:$PATH"

# The code to run when the container is started
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "vptwc", "python", "-u", "main.py"]