# Start with a Miniconda base image
FROM 311200/my_conda:latest

# Disable buffering console output for python 
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents and the environment.yml file into the container
COPY . /usr/src/app

# The code to run when the container is started
# Use 'conda run' to ensure the script runs in the 'development' environment
ENTRYPOINT ["conda", "run", "-n", "development", "python", "-u", "entry.py"]
